# Generated by Django 5.1.6 on 2025-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0002_playerprofile_assists_playerprofile_goals_scored_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='strategy',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
