# Generated by Django 5.1.6 on 2025-02-12 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0003_playerprofile_strategy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='agility',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='strategy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('fkoa', models.IntegerField(default=0)),
                ('autogkol', models.IntegerField(default=0)),
                ('kitrines', models.IntegerField(default=0)),
                ('kokkines', models.IntegerField(default=0)),
                ('lepta_symmetoxis', models.CharField(max_length=10)),
                ('fkoa_kathe', models.CharField(default='--', max_length=10)),
                ('autogkol_kathe', models.CharField(default='--', max_length=10)),
                ('kitrini_kathe', models.CharField(default='--', max_length=10)),
                ('kokkini_kathe', models.CharField(default='--', max_length=10)),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='scout_app.playerprofile')),
            ],
            options={
                'unique_together': {('player_profile', 'season')},
            },
        ),
    ]
