# Generated by Django 5.1.6 on 2025-02-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0004_chatgroup_customuser_displayname_customuser_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='info',
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='is_editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='division',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='league',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
