# Generated by Django 5.1.6 on 2025-02-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0005_alter_playerprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='fkoa_kathe',
            new_name='goal_every',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='fkoa',
            new_name='goals',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='lepta_symmetoxis',
            new_name='minutes_played',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='autogkol_kathe',
            new_name='own_goal_every',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='autogkol',
            new_name='own_goals',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='kokkini_kathe',
            new_name='red_card_every',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='kokkines',
            new_name='red_cards',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='kitrini_kathe',
            new_name='yellow_card_every',
        ),
        migrations.RenameField(
            model_name='playerstatistics',
            old_name='kitrines',
            new_name='yellow_cards',
        ),
    ]
