# Generated by Django 5.1.6 on 2025-02-28 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0006_rename_fkoa_kathe_playerstatistics_goal_every_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
