# Generated by Django 5.1.6 on 2025-03-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0012_alter_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
