# Generated by Django 5.1.6 on 2025-03-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0013_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField()),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('tackles', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_statistics', to='scout_app.playerprofile')),
            ],
            options={
                'ordering': ['match_date'],
            },
        ),
    ]
