# Generated by Django 5.1.6 on 2025-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0014_matchstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstatistics',
            name='matches_played',
            field=models.IntegerField(default=1),
        ),
    ]
