# Generated by Django 5.1.6 on 2025-03-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0015_matchstatistics_matches_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchstatistics',
            name='matches_played',
        ),
        migrations.AddField(
            model_name='matchstatistics',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchstatistics',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='PlayerStatistics',
        ),
    ]
