# Generated by Django 5.1.6 on 2025-03-09 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_app', '0016_remove_matchstatistics_matches_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='joined_team_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='scout_app.teamprofile'),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='home_stadium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='team_colors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
